#include "PlayerStrategies.h"

void testPlayerStrategies() {

    //SHOW PLAYERS CAN BE ASSIGNED DIFFERENT STRATEGIES THAT LEAD TO DIFFERENT BEHAVIOR USING THE STRATEGY DESIGN PATTERN

    //SHOW THAT A STRATEGY ADOPTED BY A PLAYER CAN BE CHANGED DYNAMICALLY DURING PLAY 
        //NEUTRAL PLAYER BECOMES AGGRESSIVE PLAYER WHEN ATTACKED (Nate)

    //SHOW THAT THE HUMAN PLAYER MAKES DECISIONS ACCORDING TO USER INTERACTION, AND COMPUTER PLAYER MAKES DECISIONS AUTOMATICALLY, WHICH ARE BOTH IMPLEMENTED USING STRATEGY PATTERN
        //HUMAN PLAYER USER INTERACTIONS (Manreet)


        //COMPUTER PLAYER USER INTERACTIONS (Shangirna or Nate)


}